
.incorporate-templates-commit:
  variables:
    FDO_DISTRIBUTION_TAG: "${HWC_TAG}--${CI_TEMPLATES_COMMIT}"

.container:
  stage: container
  extends:
    - .incorporate-templates-commit
  variables:
    FDO_REPO_SUFFIX: $CI_JOB_NAME
    # no need to pull the whole repo to build the container image
    GIT_STRATEGY: none

ubuntu/x86_64_hwc:
  extends:
    - .fdo.container-build@ubuntu
    - .container
  variables:
    FDO_DISTRIBUTION_VERSION: "24.10"
    FDO_DISTRIBUTION_EXEC: 'bash .ci/container/ubuntu/x86_64_aospless.sh'
    HWC_TAG: $UBUNTU_HWC_TAG

.set-image:
  extends:
    - .incorporate-templates-commit
  image: "$CI_REGISTRY_IMAGE/${HWC_IMAGE}:${FDO_DISTRIBUTION_TAG}"

.use-ubuntu/x86_64_hwc:
  extends:
    - .fdo.container-build@ubuntu
    - .set-image
  variables:
    HWC_TAG: $UBUNTU_HWC_TAG
    HWC_IMAGE: $UBUNTU_HWC_IMAGE
  needs:
    - ubuntu/x86_64_hwc
