workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

variables:
  DEBIAN_FRONTEND: noninteractive
  CI_TEMPLATES_COMMIT: &ci-templates-commit e195d80f35b45cc73668be3767b923fd76c70ed5
  FDO_UPSTREAM_REPO: "drm-hwcomposer/drm-hwcomposer"
  UBUNTU_HWC_IMAGE: "ubuntu/x86_64_hwc"
  UBUNTU_HWC_TAG: "20250218_hwc"

include:
  - project: 'freedesktop/ci-templates'
    ref: *ci-templates-commit
    file:
      - '/templates/ubuntu.yml'
  - local: '.ci/container/.gitlab-ci.yml'

stages:
  - container
  - build
  - tidy
  - style

build:
  stage: build
  extends:
    .use-ubuntu/x86_64_hwc
  script:
    - ln -s "${CI_PROJECT_DIR}" "/aospless/src"
    - make -C /aospless install
    - mkdir -p "${CI_PROJECT_DIR}/install/arm64"
    - cp -r /aospless/install/* "${CI_PROJECT_DIR}/install/arm64"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/install/arm64"
    expire_in: 1 week

tidy:
  stage: tidy
  extends:
    .use-ubuntu/x86_64_hwc
  script:
    - cp -r /aospless ../
    - make -j$(nproc) -k -f "${CI_PROJECT_DIR}/.ci/Makefile"

checkstyle:
  stage: style
  extends:
    .use-ubuntu/x86_64_hwc
  script: "./.ci/.gitlab-ci-checkcommit.sh"
  artifacts:
    when: on_failure
    untracked: true
  tags:
    - placeholder-job
